const assert=require('node:assert/strict');
const{spawn}=require('node:child_process');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),test=require('node:test');
const port=32148;
let server,dataDir;
async function wait(){for(let i=0;i<80;i++){try{if((await fetch(`http://127.0.0.1:${port}/health`)).ok)return}catch{}await new Promise(resolve=>setTimeout(resolve,100))}throw Error('server did not start')}
async function request(route,options={},cookie=''){const response=await fetch(`http://127.0.0.1:${port}${route}`,{headers:{'Content-Type':'application/json',...(cookie?{cookie}:{})},...options});const text=await response.text();return{response,data:text?JSON.parse(text):null,cookie:response.headers.get('set-cookie')?.split(';')[0]||cookie}}
test.before(async()=>{dataDir=fs.mkdtempSync(path.join(os.tmpdir(),'trades-auth-test-'));server=spawn(process.execPath,['server.js'],{cwd:path.resolve(__dirname,'..'),env:{...process.env,PORT:String(port),DATA_DIR:dataDir,TRADES_ADMIN_EMAILS:'owner@example.com',ADMIN_MAGIC_LINK_PREVIEW:'true'},stdio:'ignore'});await wait()});
test.after(()=>{server.kill();fs.rmSync(dataDir,{recursive:true,force:true})});
test('signup and existing-account sign-in sessions both open the dashboard',async()=>{const signup=await request('/api/signup',{method:'POST',body:JSON.stringify({fullName:'Auth Tester',companyName:'Auth Test Co',city:'Dallas',state:'tx',trades:['electrical'],email:'auth@example.com',password:'test-password',capabilities:['subcontractor']})});assert.equal(signup.response.status,201);assert.deepEqual(signup.data.company.trades,['Electrical']);assert.equal(signup.data.company.state,'TX');assert.match(signup.cookie,/^trades_session=/);assert.equal((await request('/api/dashboard',{},signup.cookie)).response.status,200);assert.equal((await request('/api/logout',{method:'POST'},signup.cookie)).response.status,200);const login=await request('/api/login',{method:'POST',body:JSON.stringify({email:' AUTH@example.com ',password:'test-password'})});assert.equal(login.response.status,200);assert.match(login.cookie,/^trades_session=/);assert.equal((await request('/api/me',{},login.cookie)).response.status,200);assert.equal((await request('/api/dashboard',{},login.cookie)).response.status,200)});
test('server rejects nonstandard trades and normalizes canonical job trades',async()=>{const invalid=await request('/api/signup',{method:'POST',body:JSON.stringify({fullName:'Invalid Trade',companyName:'Invalid Co',city:'Dallas',state:'TX',trades:['Sparky'],email:'invalid@example.com',password:'test-password',capabilities:['contractor']})});assert.equal(invalid.response.status,400);assert.match(invalid.data.error,/standard trade list/);const job=await request('/api/jobs',{method:'POST',body:JSON.stringify({title:'Electrical rough-in',trade:'electrical',city:'Dallas',state:'tx',description:'Rough-in work.'})},(await request('/api/login',{method:'POST',body:JSON.stringify({email:'auth@example.com',password:'test-password'})})).cookie);assert.equal(job.response.status,403)});
test('public picker configuration exposes only the original 22 launch trades',async()=>{const config=await request('/api/public-config');assert.equal(config.response.status,200);assert.equal(config.data.trades.length,22);assert.ok(config.data.trades.includes('Framing and Rough Carpentry'));assert.ok(config.data.trades.includes('Cleaning, Hauling, and Final Jobsite Cleanup'));assert.ok(!config.data.trades.includes('Appliance Installation'));assert.equal(typeof config.data.googleMapsApiKey,'string')});
test('login distinguishes a missing account from an incorrect password',async()=>{const missing=await request('/api/login',{method:'POST',body:JSON.stringify({email:'missing@example.com',password:'test-password'})});assert.equal(missing.response.status,404);assert.equal(missing.data.code,'account_not_found');const wrong=await request('/api/login',{method:'POST',body:JSON.stringify({email:'auth@example.com',password:'wrong-password'})});assert.equal(wrong.response.status,401);assert.equal(wrong.data.code,'incorrect_password')});
test('configured data directory is reported as persistent storage',async()=>{const status=await request('/api/storage/status');assert.equal(status.response.status,200);assert.equal(status.data.persistent,true);assert.equal(status.data.provider,'configured-directory')});
test('served account and dashboard pages include standardized picker scripts',async()=>{const account=await fetch(`http://127.0.0.1:${port}/signup`).then(response=>response.text()),dashboardResponse=await fetch(`http://127.0.0.1:${port}/dashboard`),dashboard=await dashboardResponse.text(),dashboardScript=await fetch(`http://127.0.0.1:${port}/dashboard.js`).then(response=>response.text()),roleGuard=await fetch(`http://127.0.0.1:${port}/dashboard-bridge.js`).then(response=>response.text());assert.match(account,/taxonomy\.js/);assert.match(account,/data-trade-picker="multi"/);assert.match(dashboard,/taxonomy\.js/);assert.match(dashboardScript,/error\.status===401/);assert.doesNotMatch(dashboardScript,/\.catch\(\(\)=>\{location\.href='\/login'\}\)/);assert.match(roleGuard,/subcontractorOnly/);assert.match(roleGuard,/postForm.*postedJobs/);assert.equal(dashboardResponse.headers.get('cache-control'),'no-cache')});
test('dashboard views have unique routes and route-aware navigation',async()=>{for(const route of ['/dashboard','/jobs','/messages','/network','/profile','/calendar','/notifications'])assert.equal((await fetch(`http://127.0.0.1:${port}${route}`)).status,200);const html=await fetch(`http://127.0.0.1:${port}/dashboard`).then(response=>response.text()),bridge=await fetch(`http://127.0.0.1:${port}/dashboard-bridge.js`).then(response=>response.text());assert.match(html,/data-view="overview">Dashboard/);assert.match(html,/dashboard-bridge\.js\?v=20260613-1/);assert.match(bridge,/overview:'\/dashboard'/);assert.match(bridge,/history\.pushState/);assert.match(bridge,/header\.style\.display=name==='overview'\?'':'none'/)});
test('owner console uses isolated one-time magic-link sessions',async()=>{const normalLogin=await request('/api/login',{method:'POST',body:JSON.stringify({email:'auth@example.com',password:'test-password'})});assert.equal((await request('/api/admin',{},normalLogin.cookie)).response.status,401);const unauthorized=await request('/api/admin/magic/request',{method:'POST',body:JSON.stringify({email:'regular@example.com'})});assert.equal(unauthorized.response.status,200);assert.equal(unauthorized.data.magicPath,undefined);const requested=await request('/api/admin/magic/request',{method:'POST',body:JSON.stringify({email:'owner@example.com'})});assert.equal(requested.response.status,200);assert.match(requested.data.magicPath,/^\/admin\/verify\?token=/);const token=new URL(`http://local${requested.data.magicPath}`).searchParams.get('token');const verified=await request('/api/admin/magic/verify',{method:'POST',body:JSON.stringify({token})});assert.equal(verified.response.status,200);assert.match(verified.cookie,/^trades_admin_session=/);const dashboard=await request('/api/admin',{},verified.cookie);assert.equal(dashboard.response.status,200);assert.equal(dashboard.data.metrics.users,1);assert.equal(dashboard.data.owner.email,'owner@example.com');assert.equal('passwordHash' in dashboard.data.companies[0].owner,false);assert.equal((await request('/api/admin/magic/verify',{method:'POST',body:JSON.stringify({token})})).response.status,400);assert.equal((await request('/api/admin/logout',{method:'POST'},verified.cookie)).response.status,200);assert.equal((await request('/api/admin',{},verified.cookie)).response.status,401);const html=await fetch(`http://127.0.0.1:${port}/admin/login`).then(response=>response.text());assert.match(html,/Sign in with a magic link/);assert.match(html,/admin-login\.js\?v=20260613-admin2/)});
