const assert=require('node:assert/strict');
const{spawn}=require('node:child_process');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),test=require('node:test');
const port=32148;
let server,dataDir;
async function wait(){for(let i=0;i<80;i++){try{if((await fetch(`http://127.0.0.1:${port}/health`)).ok)return}catch{}await new Promise(resolve=>setTimeout(resolve,100))}throw Error('server did not start')}
async function request(route,options={},cookie=''){const response=await fetch(`http://127.0.0.1:${port}${route}`,{headers:{'Content-Type':'application/json',...(cookie?{cookie}:{})},...options});const text=await response.text();return{response,data:text?JSON.parse(text):null,cookie:response.headers.get('set-cookie')?.split(';')[0]||cookie}}
test.before(async()=>{dataDir=fs.mkdtempSync(path.join(os.tmpdir(),'trades-auth-test-'));server=spawn(process.execPath,['reset-server.js'],{cwd:path.resolve(__dirname,'..'),env:{...process.env,PORT:String(port),DATA_DIR:dataDir},stdio:'ignore'});await wait()});
test.after(()=>{server.kill();fs.rmSync(dataDir,{recursive:true,force:true})});
test('signup and existing-account sign-in sessions both open the dashboard',async()=>{const signup=await request('/api/signup',{method:'POST',body:JSON.stringify({fullName:'Auth Tester',companyName:'Auth Test Co',city:'Dallas',state:'TX',trades:['Electrical'],email:'auth@example.com',password:'test-password',capabilities:['subcontractor']})});assert.equal(signup.response.status,201);assert.match(signup.cookie,/^trades_session=/);assert.equal((await request('/api/dashboard',{},signup.cookie)).response.status,200);assert.equal((await request('/api/logout',{method:'POST'},signup.cookie)).response.status,200);const login=await request('/api/login',{method:'POST',body:JSON.stringify({email:' AUTH@example.com ',password:'test-password'})});assert.equal(login.response.status,200);assert.match(login.cookie,/^trades_session=/);assert.equal((await request('/api/me',{},login.cookie)).response.status,200);assert.equal((await request('/api/dashboard',{},login.cookie)).response.status,200)});
test('login distinguishes a missing account from an incorrect password',async()=>{const missing=await request('/api/login',{method:'POST',body:JSON.stringify({email:'missing@example.com',password:'test-password'})});assert.equal(missing.response.status,404);assert.equal(missing.data.code,'account_not_found');const wrong=await request('/api/login',{method:'POST',body:JSON.stringify({email:'auth@example.com',password:'wrong-password'})});assert.equal(wrong.response.status,401);assert.equal(wrong.data.code,'incorrect_password')});
test('configured data directory is reported as persistent storage',async()=>{const status=await request('/api/storage/status');assert.equal(status.response.status,200);assert.equal(status.data.persistent,true);assert.equal(status.data.provider,'configured-directory')});
test('served account and dashboard scripts do not contain competing auth redirects',async()=>{const account=await fetch(`http://127.0.0.1:${port}/account.js`).then(response=>response.text()),dashboard=await fetch(`http://127.0.0.1:${port}/dashboard.js`).then(response=>response.text());assert.doesNotMatch(account,/fetch\('\/api\/me'/);assert.match(dashboard,/error\.status===401/);assert.doesNotMatch(dashboard,/\.catch\(\(\)=>\{location\.href='\/login'\}\)/)});
