const{spawn}=require('node:child_process');
const crypto=require('node:crypto'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const port=Number(process.env.PORT||3000),innerPort=port+1,dataRoot=path.resolve(process.env.DATA_DIR||path.join(__dirname,'data')),dataFile=path.join(dataRoot,'store.json'),dashboardRoutes=['/dashboard','/jobs','/messages','/network','/profile','/calendar'];
const child=spawn(process.execPath,['server.js'],{cwd:__dirname,env:{...process.env,PORT:String(innerPort),DATA_DIR:dataRoot},stdio:'inherit'});
function blank(){return{users:[],companies:[],memberships:[],sessions:[],portfolioProjects:[],credentials:[],jobs:[],bids:[],conversations:[],messages:[]}}
function read(){fs.mkdirSync(dataRoot,{recursive:true});if(!fs.existsSync(dataFile))fs.writeFileSync(dataFile,JSON.stringify(blank()));return{...blank(),...JSON.parse(fs.readFileSync(dataFile,'utf8'))}}
function write(s){const t=`${dataFile}.${crypto.randomUUID()}.tmp`;fs.writeFileSync(t,JSON.stringify(s,null,2));fs.renameSync(t,dataFile)}
function clean(v,n=300){return String(v||'').trim().slice(0,n)}
function id(p){return`${p}_${crypto.randomUUID()}`}
function cookies(r){return Object.fromEntries(String(r.headers.cookie||'').split(';').map(x=>x.trim().split('=')).filter(x=>x.length===2))}
function context(r,s){const q=s.sessions.find(x=>x.token===cookies(r).trades_session&&x.expiresAt>new Date().toISOString()),u=s.users.find(x=>x.id===q?.userId),m=s.memberships.find(x=>x.userId===u?.id),c=s.companies.find(x=>x.id===m?.companyId);return u&&c?{user:u,company:c}:null}
function body(r){return new Promise((ok,no)=>{let b='';r.on('data',x=>{b+=x;if(b.length>1e6)no(Error('large'))});r.on('end',()=>{try{ok(JSON.parse(b||'{}'))}catch{no(Error('json'))}})})}
function json(r,n,v){r.writeHead(n,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});r.end(JSON.stringify(v))}
function send(r,n,v,type='text/plain; charset=utf-8',extra={}){r.writeHead(n,{'Content-Type':type,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...extra});r.end(v)}
function validUrl(v){try{const u=new URL(v);return['http:','https:'].includes(u.protocol)?u.toString():''}catch{return''}}
function sameMarket(item,company){return clean(item.city,80).toLowerCase()===clean(company.city,80).toLowerCase()&&clean(item.state,2).toUpperCase()===clean(company.state,2).toUpperCase()}
function proxy(req,res,onJson){const p=http.request({hostname:'127.0.0.1',port:innerPort,path:req.url,method:req.method,headers:req.headers},x=>{if(!onJson){res.writeHead(x.statusCode,x.headers);return x.pipe(res)}let chunks=[];x.on('data',chunk=>chunks.push(chunk));x.on('end',()=>{const raw=Buffer.concat(chunks);if(x.statusCode>=200&&x.statusCode<300){try{const value=onJson(JSON.parse(raw.toString('utf8'))),output=Buffer.from(JSON.stringify(value));res.writeHead(x.statusCode,{...x.headers,'content-length':output.length});return res.end(output)}catch(error){console.error(error)}}res.writeHead(x.statusCode,x.headers);res.end(raw)})});p.on('error',()=>json(res,503,{error:'Application starting. Please retry.'}));req.pipe(p)}
function date(v){return /^\d{4}-\d{2}-\d{2}$/.test(clean(v,10))?clean(v,10):''}
function addDay(value){const d=new Date(`${value}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+1);return d.toISOString().slice(0,10)}
function compact(value){return value.replaceAll('-','')}
function companyPublic(c){return{id:c.id,name:c.name,city:c.city,state:c.state,capabilities:c.capabilities,trades:c.trades}}
function calendarParticipant(job,companyId){return job.status==='awarded'&&(job.postingCompanyId===companyId||job.awardedCompanyId===companyId)}
function calendarEvent(s,job,companyId){const partnerId=job.postingCompanyId===companyId?job.awardedCompanyId:job.postingCompanyId,partner=s.companies.find(x=>x.id===partnerId),details=`${job.trade} project with ${partner?.name||'trade partner'}. ${job.calendarNotes||job.description||''}`.trim(),location=`${job.city}, ${job.state}`,endExclusive=addDay(job.endDate),params={text:job.title,dates:`${compact(job.startDate)}/${compact(endExclusive)}`,details,location},outlook={path:'/calendar/action/compose',rru:'addevent',subject:job.title,startdt:job.startDate,enddt:endExclusive,allday:'true',body:details,location};return{...job,partnerCompany:companyPublic(partner),googleUrl:`https://calendar.google.com/calendar/render?action=TEMPLATE&${new URLSearchParams(params)}`,outlookUrl:`https://outlook.live.com/calendar/0/deeplink/compose?${new URLSearchParams(outlook)}`,icsPath:`/api/calendar/jobs/${job.id}.ics`}}
function icsEscape(value){return String(value||'').replaceAll('\\','\\\\').replaceAll(';','\\;').replaceAll(',','\\,').replace(/\r?\n/g,'\\n')}
function calendarIcs(s,job,companyId){const event=calendarEvent(s,job,companyId);return['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Trades//Shared Project Calendar//EN','CALSCALE:GREGORIAN','METHOD:PUBLISH','BEGIN:VEVENT',`UID:${job.id}@trades.app`,`DTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'')}`,`DTSTART;VALUE=DATE:${compact(job.startDate)}`,`DTEND;VALUE=DATE:${compact(addDay(job.endDate))}`,`SUMMARY:${icsEscape(job.title)}`,`DESCRIPTION:${icsEscape(`${job.trade} project with ${event.partnerCompany.name}. ${job.calendarNotes||job.description||''}`)}`,`LOCATION:${icsEscape(`${job.city}, ${job.state}`)}`,'END:VEVENT','END:VCALENDAR',''].join('\r\n')}
async function calendarApi(req,res,u){const s=read(),c=context(req,s);if(!c)return json(res,401,{error:'Sign in required'});if(req.method==='GET'&&u.pathname==='/api/calendar')return json(res,200,{events:s.jobs.filter(job=>calendarParticipant(job,c.company.id)&&job.startDate&&job.endDate).map(job=>calendarEvent(s,job,c.company.id))});const award=u.pathname.match(/^\/api\/jobs\/([^/]+)\/award$/);if(req.method==='POST'&&award){const job=s.jobs.find(x=>x.id===award[1]),b=await body(req),bid=s.bids.find(x=>x.id===b.bidId&&x.jobId===job?.id),startDate=date(b.startDate),endDate=date(b.endDate);if(!job||job.postingCompanyId!==c.company.id)return json(res,403,{error:'Only the posting contractor can award this job.'});if(job.status!=='published'||!bid)return json(res,400,{error:'Choose a valid open bid.'});if(!startDate||!endDate||endDate<startDate)return json(res,400,{error:'Choose valid project start and end dates.'});Object.assign(job,{status:'awarded',awardedBidId:bid.id,awardedCompanyId:bid.biddingCompanyId,startDate,endDate,calendarNotes:clean(b.calendarNotes,1200),awardedAt:new Date().toISOString()});s.bids.filter(x=>x.jobId===job.id).forEach(x=>{x.status=x.id===bid.id?'accepted':'declined';x.updatedAt=new Date().toISOString()});let conversation=s.conversations.find(x=>x.companyIds.includes(job.postingCompanyId)&&x.companyIds.includes(job.awardedCompanyId));if(!conversation)s.conversations.push({id:id('cnv'),companyIds:[job.postingCompanyId,job.awardedCompanyId],jobId:job.id,createdAt:new Date().toISOString()});write(s);return json(res,200,{event:calendarEvent(s,job,c.company.id)})}const update=u.pathname.match(/^\/api\/calendar\/jobs\/([^/.]+)$/);if(req.method==='PUT'&&update){const job=s.jobs.find(x=>x.id===update[1]),b=await body(req),startDate=date(b.startDate),endDate=date(b.endDate);if(!job||!calendarParticipant(job,c.company.id))return json(res,403,{error:'This project is not on your shared calendar.'});if(!startDate||!endDate||endDate<startDate)return json(res,400,{error:'Choose valid project start and end dates.'});job.startDate=startDate;job.endDate=endDate;job.calendarNotes=clean(b.calendarNotes,1200);job.scheduleUpdatedAt=new Date().toISOString();write(s);return json(res,200,{event:calendarEvent(s,job,c.company.id)})}const download=u.pathname.match(/^\/api\/calendar\/jobs\/([^/.]+)\.ics$/);if(req.method==='GET'&&download){const job=s.jobs.find(x=>x.id===download[1]);if(!job||!calendarParticipant(job,c.company.id))return json(res,404,{error:'Calendar event not found.'});return send(res,200,calendarIcs(s,job,c.company.id),'text/calendar; charset=utf-8',{'Content-Disposition':`attachment; filename="trades-${job.id}.ics"`})}return json(res,404,{error:'Calendar route not found.'})}
async function profiles(req,res,u){const s=read(),c=context(req,s);if(!c)return json(res,401,{error:'Sign in required'});if(req.method==='PUT'&&u.pathname==='/api/profile/location'){const b=await body(req),city=clean(b.city,80),state=clean(b.state,2).toUpperCase();if(!city||state.length!==2)return json(res,400,{error:'Enter a city and two-letter state.'});c.company.city=city;c.company.state=state;write(s);return json(res,200,{company:{id:c.company.id,name:c.company.name,city,state,capabilities:c.company.capabilities,trades:c.company.trades}})}const match=u.pathname.match(/^\/api\/profiles\/([^/]+)$/);if(match&&req.method==='GET'){const target=s.companies.find(x=>x.id===match[1]);if(!target||(!target.capabilities.includes('subcontractor')&&target.id!==c.company.id))return json(res,404,{error:'Subcontractor profile not found.'});return json(res,200,{company:companyPublic(target),portfolio:s.portfolioProjects.filter(x=>x.companyId===target.id),credentials:s.credentials.filter(x=>x.companyId===target.id).map(({privateDocumentUrl,...x})=>x),isOwner:target.id===c.company.id})}if(req.method==='POST'&&u.pathname==='/api/profile/portfolio'){if(!c.company.capabilities.includes('subcontractor'))return json(res,403,{error:'Enable subcontractor capability to publish completed work.'});const b=await body(req),title=clean(b.title,160),photoUrl=validUrl(b.photoUrl);if(!title||!photoUrl)return json(res,400,{error:'Add a project title and valid image URL.'});const p={id:id('por'),companyId:c.company.id,title,trade:clean(b.trade,100),city:clean(b.city,80),state:clean(b.state,2).toUpperCase(),completedAt:clean(b.completedAt,20),description:clean(b.description,1500),photoUrl,createdAt:new Date().toISOString()};s.portfolioProjects.push(p);write(s);return json(res,201,{project:p})}if(req.method==='POST'&&u.pathname==='/api/profile/credentials'){if(!c.company.capabilities.includes('subcontractor'))return json(res,403,{error:'Enable subcontractor capability to publish credentials.'});const b=await body(req),type=['license','insurance','certification','bond'].includes(b.type)?b.type:'',name=clean(b.name,160);if(!type||!name)return json(res,400,{error:'Choose a credential type and name.'});const x={id:id('cred'),companyId:c.company.id,type,name,issuer:clean(b.issuer,160),credentialNumber:clean(b.credentialNumber,100),state:clean(b.state,2).toUpperCase(),expiresAt:clean(b.expiresAt,20),coverage:clean(b.coverage,160),notes:clean(b.notes,1000),verificationStatus:'self-reported',createdAt:new Date().toISOString()};s.credentials.push(x);write(s);return json(res,201,{credential:x})}return json(res,404,{error:'Profile route not found.'})}
const server=http.createServer((req,res)=>{const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(u.pathname.startsWith('/api/calendar')||/^\/api\/jobs\/[^/]+\/award$/.test(u.pathname))return calendarApi(req,res,u);if(u.pathname.startsWith('/api/profile'))return profiles(req,res,u);if(req.method==='GET'&&u.pathname==='/api/dashboard'){const s=read(),c=context(req,s);return proxy(req,res,data=>{if(!c)return data;data.availableJobs=(data.availableJobs||[]).filter(job=>sameMarket(job,c.company));data.directory=(data.directory||[]).filter(company=>sameMarket(company,c.company));data.marketplaceLocation={city:c.company.city,state:c.company.state};return data})}if(dashboardRoutes.includes(u.pathname)){const html=fs.readFileSync(path.join(__dirname,'prototype','dashboard.html'),'utf8').replace('</body>','<script src="profile.js"></script><script src="location.js"></script><script src="calendar.js"></script></body>');res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-cache'});return res.end(html)}return proxy(req,res)});
server.listen(port,'0.0.0.0',()=>console.log(`Trades profile gateway listening on ${port}`));
for(const sig of['SIGTERM','SIGINT'])process.on(sig,()=>{child.kill(sig);server.close()});
