const{spawn}=require('node:child_process');
const crypto=require('node:crypto'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const port=Number(process.env.PORT||3000),innerPort=port+1,dataRoot=path.resolve(process.env.DATA_DIR||path.join(__dirname,'data')),dataFile=path.join(dataRoot,'store.json'),dashboardRoutes=['/dashboard','/jobs','/messages','/network','/profile'];
const child=spawn(process.execPath,['server.js'],{cwd:__dirname,env:{...process.env,PORT:String(innerPort),DATA_DIR:dataRoot},stdio:'inherit'});
function blank(){return{users:[],companies:[],memberships:[],sessions:[],portfolioProjects:[],credentials:[]}}
function read(){fs.mkdirSync(dataRoot,{recursive:true});if(!fs.existsSync(dataFile))fs.writeFileSync(dataFile,JSON.stringify(blank()));return{...blank(),...JSON.parse(fs.readFileSync(dataFile,'utf8'))}}
function write(s){const t=`${dataFile}.${crypto.randomUUID()}.tmp`;fs.writeFileSync(t,JSON.stringify(s,null,2));fs.renameSync(t,dataFile)}
function clean(v,n=300){return String(v||'').trim().slice(0,n)}
function id(p){return`${p}_${crypto.randomUUID()}`}
function cookies(r){return Object.fromEntries(String(r.headers.cookie||'').split(';').map(x=>x.trim().split('=')).filter(x=>x.length===2))}
function context(r,s){const q=s.sessions.find(x=>x.token===cookies(r).trades_session&&x.expiresAt>new Date().toISOString()),u=s.users.find(x=>x.id===q?.userId),m=s.memberships.find(x=>x.userId===u?.id),c=s.companies.find(x=>x.id===m?.companyId);return u&&c?{user:u,company:c}:null}
function body(r){return new Promise((ok,no)=>{let b='';r.on('data',x=>{b+=x;if(b.length>1e6)no(Error('large'))});r.on('end',()=>{try{ok(JSON.parse(b||'{}'))}catch{no(Error('json'))}})})}
function json(r,n,v){r.writeHead(n,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});r.end(JSON.stringify(v))}
function validUrl(v){try{const u=new URL(v);return['http:','https:'].includes(u.protocol)?u.toString():''}catch{return''}}
function sameMarket(item,company){return clean(item.city,80).toLowerCase()===clean(company.city,80).toLowerCase()&&clean(item.state,2).toUpperCase()===clean(company.state,2).toUpperCase()}
function proxy(req,res,onJson){const p=http.request({hostname:'127.0.0.1',port:innerPort,path:req.url,method:req.method,headers:req.headers},x=>{if(!onJson){res.writeHead(x.statusCode,x.headers);return x.pipe(res)}let chunks=[];x.on('data',chunk=>chunks.push(chunk));x.on('end',()=>{const raw=Buffer.concat(chunks);if(x.statusCode>=200&&x.statusCode<300){try{const value=onJson(JSON.parse(raw.toString('utf8')));const output=Buffer.from(JSON.stringify(value));res.writeHead(x.statusCode,{...x.headers,'content-length':output.length});return res.end(output)}catch(error){console.error(error)}}res.writeHead(x.statusCode,x.headers);res.end(raw)})});p.on('error',()=>json(res,503,{error:'Application starting. Please retry.'}));req.pipe(p)}
async function profiles(req,res,u){const s=read(),c=context(req,s);if(!c)return json(res,401,{error:'Sign in required'});if(req.method==='PUT'&&u.pathname==='/api/profile/location'){const b=await body(req),city=clean(b.city,80),state=clean(b.state,2).toUpperCase();if(!city||state.length!==2)return json(res,400,{error:'Enter a city and two-letter state.'});c.company.city=city;c.company.state=state;write(s);return json(res,200,{company:{id:c.company.id,name:c.company.name,city,state,capabilities:c.company.capabilities,trades:c.company.trades}})}const match=u.pathname.match(/^\/api\/profiles\/([^/]+)$/);if(match&&req.method==='GET'){const target=s.companies.find(x=>x.id===match[1]);if(!target||(!target.capabilities.includes('subcontractor')&&target.id!==c.company.id))return json(res,404,{error:'Subcontractor profile not found.'});return json(res,200,{company:{id:target.id,name:target.name,city:target.city,state:target.state,trades:target.trades,capabilities:target.capabilities},portfolio:s.portfolioProjects.filter(x=>x.companyId===target.id),credentials:s.credentials.filter(x=>x.companyId===target.id).map(({privateDocumentUrl,...x})=>x),isOwner:target.id===c.company.id})}if(req.method==='POST'&&u.pathname==='/api/profile/portfolio'){if(!c.company.capabilities.includes('subcontractor'))return json(res,403,{error:'Enable subcontractor capability to publish completed work.'});const b=await body(req),title=clean(b.title,160),photoUrl=validUrl(b.photoUrl);if(!title||!photoUrl)return json(res,400,{error:'Add a project title and valid image URL.'});const p={id:id('por'),companyId:c.company.id,title,trade:clean(b.trade,100),city:clean(b.city,80),state:clean(b.state,2).toUpperCase(),completedAt:clean(b.completedAt,20),description:clean(b.description,1500),photoUrl,createdAt:new Date().toISOString()};s.portfolioProjects.push(p);write(s);return json(res,201,{project:p})}if(req.method==='POST'&&u.pathname==='/api/profile/credentials'){if(!c.company.capabilities.includes('subcontractor'))return json(res,403,{error:'Enable subcontractor capability to publish credentials.'});const b=await body(req),type=['license','insurance','certification','bond'].includes(b.type)?b.type:'',name=clean(b.name,160);if(!type||!name)return json(res,400,{error:'Choose a credential type and name.'});const x={id:id('cred'),companyId:c.company.id,type,name,issuer:clean(b.issuer,160),credentialNumber:clean(b.credentialNumber,100),state:clean(b.state,2).toUpperCase(),expiresAt:clean(b.expiresAt,20),coverage:clean(b.coverage,160),notes:clean(b.notes,1000),verificationStatus:'self-reported',createdAt:new Date().toISOString()};s.credentials.push(x);write(s);return json(res,201,{credential:x})}return json(res,404,{error:'Profile route not found.'})}
const server=http.createServer((req,res)=>{const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(u.pathname.startsWith('/api/profile'))return profiles(req,res,u);if(req.method==='GET'&&u.pathname==='/api/dashboard'){const s=read(),c=context(req,s);return proxy(req,res,data=>{if(!c)return data;data.availableJobs=(data.availableJobs||[]).filter(job=>sameMarket(job,c.company));data.directory=(data.directory||[]).filter(company=>sameMarket(company,c.company));data.marketplaceLocation={city:c.company.city,state:c.company.state};return data})}if(dashboardRoutes.includes(u.pathname)){const html=fs.readFileSync(path.join(__dirname,'prototype','dashboard.html'),'utf8').replace('</body>','<script src="profile.js"></script><script src="location.js"></script></body>');res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-cache'});return res.end(html)}return proxy(req,res)});
server.listen(port,'0.0.0.0',()=>console.log(`Trades profile gateway listening on ${port}`));
for(const sig of['SIGTERM','SIGINT'])process.on(sig,()=>{child.kill(sig);server.close()});
