const{spawn}=require('node:child_process');
const crypto=require('node:crypto'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const port=Number(process.env.PORT||3000),innerPort=port+1,dataRoot=path.resolve(process.env.DATA_DIR||path.join(__dirname,'data')),dataFile=path.join(dataRoot,'store.json'),resetMinutes=30;
const child=spawn(process.execPath,['profile-server.js'],{cwd:__dirname,env:{...process.env,PORT:String(innerPort),DATA_DIR:dataRoot},stdio:'inherit'});
function blank(){return{users:[],sessions:[],passwordResetTokens:[]}}
function read(){fs.mkdirSync(dataRoot,{recursive:true});if(!fs.existsSync(dataFile))fs.writeFileSync(dataFile,JSON.stringify(blank()));return{...blank(),...JSON.parse(fs.readFileSync(dataFile,'utf8'))}}
function write(s){const temp=`${dataFile}.${crypto.randomUUID()}.tmp`;fs.writeFileSync(temp,JSON.stringify(s,null,2));fs.renameSync(temp,dataFile)}
function normalizeCompanies(){const store=read();let changed=false;(store.companies||[]).forEach(company=>{if(!Array.isArray(company.capabilities)){company.capabilities=[];changed=true}if(!Array.isArray(company.trades)){company.trades=[];changed=true}if(typeof company.city!=='string'){company.city='';changed=true}if(typeof company.state!=='string'){company.state='';changed=true}if(!Number.isFinite(company.serviceRadius)){company.serviceRadius=50;changed=true}});if(changed)write(store)}
function clean(value,max=300){return String(value||'').trim().slice(0,max)}
function email(value){return clean(value,254).toLowerCase()}
function tokenHash(value){return crypto.createHash('sha256').update(value).digest('hex')}
function passwordHash(password,salt=crypto.randomBytes(16).toString('hex')){return{salt,hash:crypto.scryptSync(password,salt,64).toString('hex')}}
function body(req){return new Promise((resolve,reject)=>{let value='';req.on('data',chunk=>{value+=chunk;if(value.length>1e6)reject(Error('large'))});req.on('end',()=>{try{resolve(JSON.parse(value||'{}'))}catch{reject(Error('json'))}});req.on('error',reject)})}
function json(res,status,value){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(JSON.stringify(value))}
async function resetApi(req,res,url){const store=read();try{if(req.method==='POST'&&url.pathname==='/api/password/forgot'){const input=await body(req),user=store.users.find(item=>item.email===email(input.email));store.passwordResetTokens=store.passwordResetTokens.filter(item=>!item.usedAt&&item.expiresAt>new Date().toISOString());let resetPath='';if(user){store.passwordResetTokens=store.passwordResetTokens.filter(item=>item.userId!==user.id);const raw=crypto.randomBytes(32).toString('hex');store.passwordResetTokens.push({id:`rst_${crypto.randomUUID()}`,userId:user.id,tokenHash:tokenHash(raw),expiresAt:new Date(Date.now()+resetMinutes*60000).toISOString(),usedAt:null,createdAt:new Date().toISOString()});resetPath=`/reset-password?token=${raw}`}write(store);return json(res,200,{message:'If an account exists for that email, a password reset link is ready.',resetPath,delivery:process.env.PASSWORD_RESET_EMAIL_ENABLED==='true'?'email':'preview'})}if(req.method==='POST'&&url.pathname==='/api/password/reset'){const input=await body(req),password=String(input.password||''),record=store.passwordResetTokens.find(item=>item.tokenHash===tokenHash(clean(input.token,200))&&!item.usedAt&&item.expiresAt>new Date().toISOString());if(password.length<8)return json(res,400,{error:'Use a password with at least 8 characters.'});if(!record)return json(res,400,{error:'This reset link is invalid or has expired.'});const user=store.users.find(item=>item.id===record.userId);if(!user)return json(res,400,{error:'This reset link is invalid or has expired.'});const hashed=passwordHash(password);user.passwordSalt=hashed.salt;user.passwordHash=hashed.hash;record.usedAt=new Date().toISOString();store.sessions=store.sessions.filter(item=>item.userId!==user.id);write(store);return json(res,200,{message:'Your password has been updated. Sign in with your new password.'})}return json(res,404,{error:'Password reset route not found.'})}catch(error){console.error(error);return json(res,500,{error:'Something went wrong. Please try again.'})}}
function proxy(req,res,url){const accountRoute=['/forgot-password','/reset-password'].includes(url.pathname),target=accountRoute?`/login${url.search}`:req.url,headers={...req.headers,host:`127.0.0.1:${innerPort}`},p=http.request({hostname:'127.0.0.1',port:innerPort,path:target,method:req.method,headers},response=>{res.writeHead(response.statusCode,response.headers);response.pipe(res)});p.on('error',()=>json(res,503,{error:'Application starting. Please retry.'}));req.pipe(p)}
const server=http.createServer((req,res)=>{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(url.pathname.startsWith('/api/password/'))return resetApi(req,res,url);if(req.method==='GET'&&url.pathname==='/api/dashboard')normalizeCompanies();return proxy(req,res,url)});
server.listen(port,'0.0.0.0',()=>console.log(`Trades password reset gateway listening on ${port}`));
for(const signal of['SIGTERM','SIGINT'])process.on(signal,()=>{child.kill(signal);server.close()});
