const{spawn}=require('node:child_process');
const crypto=require('node:crypto'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const port=Number(process.env.PORT||3000),innerPort=port+1,dataRoot=path.resolve(process.env.DATA_DIR||process.env.RAILWAY_VOLUME_MOUNT_PATH||path.join(__dirname,'data')),dataFile=path.join(dataRoot,'store.json'),resetMinutes=30,sessionHours=336,persistentStorage=Boolean(process.env.DATA_DIR||process.env.RAILWAY_VOLUME_MOUNT_PATH);
const trades=['Appliance Installation','Asphalt Paving','Cabinetry','Carpentry','Cleaning','Concrete','Countertops','Demolition','Doors and Windows','Drywall','Electrical','Excavation','Fencing','Finish Carpentry','Fire Protection','Flooring','Framing','General Labor','Glass and Glazing','Gutters','HVAC','Insulation','Landscaping','Masonry','Metal Fabrication','Painting','Plumbing','Pool and Spa','Roofing','Siding','Solar','Stone and Tile','Structural Steel','Surveying','Waterproofing','Welding'];
const child=spawn(process.execPath,['profile-server.js'],{cwd:__dirname,env:{...process.env,PORT:String(innerPort),DATA_DIR:dataRoot},stdio:'inherit'});
function blank(){return{users:[],sessions:[],passwordResetTokens:[]}}
function read(){fs.mkdirSync(dataRoot,{recursive:true});if(!fs.existsSync(dataFile))fs.writeFileSync(dataFile,JSON.stringify(blank()));return{...blank(),...JSON.parse(fs.readFileSync(dataFile,'utf8'))}}
function write(s){const temp=`${dataFile}.${crypto.randomUUID()}.tmp`;fs.writeFileSync(temp,JSON.stringify(s,null,2));fs.renameSync(temp,dataFile)}
function normalizeCompanies(){const store=read();let changed=false;(store.companies||[]).forEach(company=>{if(!Array.isArray(company.capabilities)){company.capabilities=[];changed=true}if(!Array.isArray(company.trades)){company.trades=[];changed=true}if(typeof company.city!=='string'){company.city='';changed=true}if(typeof company.state!=='string'){company.state='';changed=true}if(!Number.isFinite(company.serviceRadius)){company.serviceRadius=50;changed=true}});if(changed)write(store)}
function clean(value,max=300){return String(value||'').trim().slice(0,max)}
function email(value){return clean(value,254).toLowerCase()}
function canonicalTrade(value){const normalized=clean(value,100).toLowerCase();return trades.find(trade=>trade.toLowerCase()===normalized)||''}
function normalizeMarketplaceInput(input){const value={...input};if(Array.isArray(value.trades)){const normalized=value.trades.map(canonicalTrade).filter(Boolean);if(value.trades.length&&!normalized.length)throw Error('Select trades from the standard trade list.');value.trades=[...new Set(normalized)]}if(Object.hasOwn(value,'trade')&&clean(value.trade)){const normalized=canonicalTrade(value.trade);if(!normalized)throw Error('Select a trade from the standard trade list.');value.trade=normalized}if(Object.hasOwn(value,'city'))value.city=clean(value.city,80);if(Object.hasOwn(value,'state'))value.state=clean(value.state,2).toUpperCase();return value}
function tokenHash(value){return crypto.createHash('sha256').update(value).digest('hex')}
function passwordHash(password,salt=crypto.randomBytes(16).toString('hex')){return{salt,hash:crypto.scryptSync(password,salt,64).toString('hex')}}
function passwordMatches(password,user){if(!user.passwordSalt||!user.passwordHash)return false;const actual=crypto.scryptSync(password,user.passwordSalt,64),expected=Buffer.from(user.passwordHash,'hex');return actual.length===expected.length&&crypto.timingSafeEqual(actual,expected)}
function body(req){return new Promise((resolve,reject)=>{let value='';req.on('data',chunk=>{value+=chunk;if(value.length>1e6)reject(Error('large'))});req.on('end',()=>{try{resolve(JSON.parse(value||'{}'))}catch{reject(Error('json'))}});req.on('error',reject)})}
function sessionCookie(token,age=sessionHours*3600){return`trades_session=${encodeURIComponent(token)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${age}${process.env.NODE_ENV==='production'?'; Secure':''}`}
function json(res,status,value,extra={}){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...extra});res.end(JSON.stringify(value))}
async function loginApi(req,res){try{const store=read(),input=await body(req),user=store.users.find(item=>item.email===email(input.email));if(!user)return json(res,404,{error:'We could not find an account for that email. Accounts created before persistent storage was enabled may need to be recreated.',code:'account_not_found'});if(!passwordMatches(String(input.password||''),user))return json(res,401,{error:'The password is incorrect.',code:'incorrect_password'});const session={token:crypto.randomBytes(32).toString('hex'),userId:user.id,expiresAt:new Date(Date.now()+sessionHours*3600e3).toISOString()},membership=(store.memberships||[]).find(item=>item.userId===user.id),company=(store.companies||[]).find(item=>item.id===membership?.companyId);if(!company)return json(res,409,{error:'This account needs support before it can sign in.'});store.sessions=store.sessions.filter(item=>item.expiresAt>new Date().toISOString());store.sessions.push(session);write(store);return json(res,200,{user:{id:user.id,email:user.email,fullName:user.fullName},company:{id:company.id,name:company.name,city:company.city||'',state:company.state||'',capabilities:Array.isArray(company.capabilities)?company.capabilities:[],trades:Array.isArray(company.trades)?company.trades:[],serviceRadius:company.serviceRadius||50}},{'Set-Cookie':sessionCookie(session.token)})}catch(error){console.error(error);return json(res,500,{error:'Sign in could not be completed. Please try again.'})}}
async function resetApi(req,res,url){const store=read();try{if(req.method==='POST'&&url.pathname==='/api/password/forgot'){const input=await body(req),user=store.users.find(item=>item.email===email(input.email));store.passwordResetTokens=store.passwordResetTokens.filter(item=>!item.usedAt&&item.expiresAt>new Date().toISOString());let resetPath='';if(user){store.passwordResetTokens=store.passwordResetTokens.filter(item=>item.userId!==user.id);const raw=crypto.randomBytes(32).toString('hex');store.passwordResetTokens.push({id:`rst_${crypto.randomUUID()}`,userId:user.id,tokenHash:tokenHash(raw),expiresAt:new Date(Date.now()+resetMinutes*60000).toISOString(),usedAt:null,createdAt:new Date().toISOString()});resetPath=`/reset-password?token=${raw}`}write(store);return json(res,200,{message:'If an account exists for that email, a password reset link is ready.',resetPath,delivery:process.env.PASSWORD_RESET_EMAIL_ENABLED==='true'?'email':'preview'})}if(req.method==='POST'&&url.pathname==='/api/password/reset'){const input=await body(req),password=String(input.password||''),record=store.passwordResetTokens.find(item=>item.tokenHash===tokenHash(clean(input.token,200))&&!item.usedAt&&item.expiresAt>new Date().toISOString());if(password.length<8)return json(res,400,{error:'Use a password with at least 8 characters.'});if(!record)return json(res,400,{error:'This reset link is invalid or has expired.'});const user=store.users.find(item=>item.id===record.userId);if(!user)return json(res,400,{error:'This reset link is invalid or has expired.'});const hashed=passwordHash(password);user.passwordSalt=hashed.salt;user.passwordHash=hashed.hash;record.usedAt=new Date().toISOString();store.sessions=store.sessions.filter(item=>item.userId!==user.id);write(store);return json(res,200,{message:'Your password has been updated. Sign in with your new password.'})}return json(res,404,{error:'Password reset route not found.'})}catch(error){console.error(error);return json(res,500,{error:'Something went wrong. Please try again.'})}}
function repairDashboardScript(source){return source.replace("if(!response.ok)throw new Error(data.error||'Request failed');return data}","if(!response.ok){const error=new Error(data.error||'Request failed');error.status=response.status;throw error}return data}").replace(".catch(()=>{location.href='/login'});",".catch(error=>{if(error.status===401)location.replace('/login');else showNotice(error.message||'Dashboard could not load. Please refresh.',true)});")}
function repairAccountScript(source){return source.replace(/const recentLogin=[\s\S]*$/,'')}
function secureHeaders(headers){const output={...headers};if(output['content-security-policy'])output['content-security-policy']=output['content-security-policy'].replace("script-src 'self'","script-src 'self' https://maps.googleapis.com https://maps.gstatic.com").replace("style-src 'self'","style-src 'self' 'unsafe-inline' https://maps.googleapis.com").replace("img-src 'self' data:","img-src 'self' data: https://maps.gstatic.com https://maps.googleapis.com").replace("connect-src 'self'","connect-src 'self' https://maps.googleapis.com");return output}
function injectDashboardPickers(source){return source.replace('</head>','<link rel="stylesheet" href="taxonomy.css?v=20260612-1"></head>').replace(/<script src="dashboard\.js[^>]*><\/script>/,'<script src="taxonomy.js?v=20260612-1"></script><script src="dashboard.js?v=20260612-auth2"></script>')}
function upstream(req,res,url,payload){const accountRoute=['/forgot-password','/reset-password'].includes(url.pathname),target=accountRoute?`/login${url.search}`:req.url,headers={...req.headers,host:`127.0.0.1:${innerPort}`};if(payload){headers['content-length']=Buffer.byteLength(payload);headers['content-type']='application/json'}const request=http.request({hostname:'127.0.0.1',port:innerPort,path:target,method:req.method,headers},response=>{const transformScript=req.method==='GET'&&['/dashboard.js','/account.js'].includes(url.pathname),transformDashboard=req.method==='GET'&&['/dashboard','/jobs','/messages','/network','/profile','/calendar','/notifications'].includes(url.pathname);if(transformScript||transformDashboard){const chunks=[];response.on('data',chunk=>chunks.push(chunk));response.on('end',()=>{const source=Buffer.concat(chunks).toString('utf8'),text=transformScript?(url.pathname==='/dashboard.js'?repairDashboardScript(source):repairAccountScript(source)):injectDashboardPickers(source),output=Buffer.from(text),responseHeaders={...secureHeaders(response.headers),'content-length':output.length,'cache-control':'no-store'};delete responseHeaders.etag;res.writeHead(response.statusCode,responseHeaders);res.end(output)});return}res.writeHead(response.statusCode,secureHeaders(response.headers));response.pipe(res)});request.setTimeout(15000,()=>request.destroy(Error('upstream timeout')));request.on('error',()=>{if(!res.headersSent)json(res,503,{error:'The application is taking too long to respond. Please retry.'});else res.end()});if(payload)request.end(payload);else req.pipe(request)}
async function normalizedProxy(req,res,url){try{const input=normalizeMarketplaceInput(await body(req));upstream(req,res,url,JSON.stringify(input))}catch(error){json(res,400,{error:error.message})}}
const normalizedRoutes=new Set(['/api/signup','/api/jobs','/api/profile/location','/api/profile/portfolio','/api/network/invites','/api/saved-searches']);
const server=http.createServer((req,res)=>{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(req.method==='GET'&&url.pathname==='/api/public-config')return json(res,200,{googleMapsApiKey:process.env.GOOGLE_MAPS_API_KEY||'',trades});if(req.method==='GET'&&url.pathname==='/api/storage/status')return json(res,200,{persistent:persistentStorage,provider:process.env.RAILWAY_VOLUME_MOUNT_PATH?'railway-volume':process.env.DATA_DIR?'configured-directory':'temporary-filesystem'});if(req.method==='POST'&&url.pathname==='/api/login')return loginApi(req,res);if(url.pathname.startsWith('/api/password/'))return resetApi(req,res,url);if(req.method==='GET'&&url.pathname==='/api/dashboard')normalizeCompanies();if(['POST','PUT'].includes(req.method)&&normalizedRoutes.has(url.pathname))return normalizedProxy(req,res,url);return upstream(req,res,url)});
server.listen(port,'0.0.0.0',()=>console.log(`Trades account gateway listening on ${port}; storage=${persistentStorage?'persistent':'temporary'}`));
for(const signal of['SIGTERM','SIGINT'])process.on(signal,()=>{child.kill(signal);server.close()});
