let dashboard; let activeConversationId;
const notice = document.getElementById('dashboardNotice');
async function api(path, options = {}) { const response = await fetch(path, { headers: { 'Content-Type': 'application/json' }, ...options }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Request failed'); return data; }
function initials(name) { return String(name).split(/\s+/).map(part => part[0]).join('').slice(0, 2).toUpperCase(); }
function escapeHtml(value) { return String(value || '').replace(/[&<>'"]/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[character]); }
function showNotice(message, error = false) { notice.textContent = message; notice.hidden = false; notice.classList.toggle('error', error); setTimeout(() => { notice.hidden = true; }, 3500); }
function capabilityText(company) { return company.capabilities.map(value => value === 'contractor' ? 'Hires subcontractors' : 'Finds trade work').join(' + '); }
function switchView(name) { document.querySelectorAll('[data-view]').forEach(button => button.classList.toggle('active', button.dataset.view === name)); document.querySelectorAll('.dashboard-view').forEach(view => { view.hidden = view.id !== `${name}View`; }); if (name === 'messages') renderConversations(); }
document.querySelectorAll('[data-view]').forEach(button => button.addEventListener('click', () => switchView(button.dataset.view)));
document.getElementById('signOut').addEventListener('click', async () => { await api('/api/logout', { method: 'POST' }); location.href = '/'; });
document.getElementById('primaryAction').addEventListener('click', () => switchView('network'));
function renderShell() { const { company, user, conversations, directory } = dashboard; const roles = capabilityText(company); document.getElementById('navInitials').textContent = initials(company.name); document.getElementById('navCompany').textContent = company.name; document.getElementById('navRole').textContent = roles; document.getElementById('dashboardGreeting').textContent = `Welcome back, ${user.fullName.split(' ')[0]}.`; document.getElementById('dashboardKicker').textContent = company.capabilities.length > 1 ? 'Full marketplace workspace' : company.capabilities[0] === 'contractor' ? 'Contractor workspace' : 'Subcontractor workspace'; const unread = conversations.reduce((sum, item) => sum + item.unread, 0); document.getElementById('unreadCount').textContent = unread || ''; document.getElementById('statGrid').innerHTML = `<div><span>Conversations</span><strong>${conversations.length}</strong><small>company connections</small></div><div><span>Unread messages</span><strong>${unread}</strong><small>need your attention</small></div><div><span>Network</span><strong>${directory.length}</strong><small>companies to connect with</small></div><div><span>Service area</span><strong>${escapeHtml(company.state || 'Add')}</strong><small>${escapeHtml(company.city || 'Complete profile')}</small></div>`; document.getElementById('setupSteps').innerHTML = `<div class="setup-item done"><span>1</span><div><strong>Company account created</strong><small>${escapeHtml(roles)}</small></div></div><div class="setup-item"><span>2</span><div><strong>Add credentials and insurance</strong><small>Build confidence before bidding or hiring.</small></div></div><div class="setup-item"><span>3</span><div><strong>${company.capabilities.includes('contractor') ? 'Post your first job' : 'Complete your trade portfolio'}</strong><small>Unlock the core marketplace workflow.</small></div></div>`; document.getElementById('profileCompany').textContent = company.name; document.getElementById('profileDetails').innerHTML = `<dl><div><dt>Capabilities</dt><dd>${escapeHtml(roles)}</dd></div><div><dt>Location</dt><dd>${escapeHtml([company.city, company.state].filter(Boolean).join(', '))}</dd></div><div><dt>Trades</dt><dd>${escapeHtml(company.trades.join(', ') || 'Not added yet')}</dd></div><div><dt>Account owner</dt><dd>${escapeHtml(user.fullName)} · ${escapeHtml(user.email)}</dd></div></dl>`; renderDirectory(); renderConversations(); }
function conversationMarkup(item) { return `<button type="button" class="conversation-item ${item.id === activeConversationId ? 'active' : ''}" data-conversation="${item.id}"><span class="company-mark">${initials(item.otherCompany.name)}</span><div><strong>${escapeHtml(item.otherCompany.name)}</strong><small>${escapeHtml(item.lastMessage?.body || 'Conversation ready')}</small></div>${item.unread ? `<b>${item.unread}</b>` : ''}</button>`; }
function renderConversations() { const html = dashboard.conversations.length ? dashboard.conversations.map(conversationMarkup).join('') : '<div class="list-empty">No conversations yet. Open the network to meet another company.</div>'; document.getElementById('conversationList').innerHTML = html; document.getElementById('recentConversations').innerHTML = html; document.querySelectorAll('[data-conversation]').forEach(button => button.addEventListener('click', () => openConversation(button.dataset.conversation))); }
function renderDirectory() { document.getElementById('directoryGrid').innerHTML = dashboard.directory.length ? dashboard.directory.map(company => `<article class="directory-card"><span class="company-mark">${initials(company.name)}</span><div><span class="trade-pill">${escapeHtml(company.state || 'Nationwide')}</span><h3>${escapeHtml(company.name)}</h3><p>${escapeHtml(capabilityText(company))}</p><small>${escapeHtml(company.trades.join(' · ') || 'Trades profile in progress')}</small></div><button class="button button-outline" type="button" data-connect="${company.id}">Message company</button></article>`).join('') : '<div class="list-empty">You are the first company here. The network will appear as more companies join.</div>'; document.querySelectorAll('[data-connect]').forEach(button => button.addEventListener('click', () => startConversation(button.dataset.connect))); }
async function startConversation(companyId) { try { const result = await api('/api/conversations', { method: 'POST', body: JSON.stringify({ companyId }) }); await refresh(); switchView('messages'); await openConversation(result.conversation.id); } catch (error) { showNotice(error.message, true); } }
async function openConversation(conversationId) { try { activeConversationId = conversationId; const result = await api(`/api/conversations/${conversationId}/messages`); document.getElementById('messageEmpty').hidden = true; document.getElementById('messageWorkspace').hidden = false; document.getElementById('messageInitials').textContent = initials(result.otherCompany.name); document.getElementById('messageCompany').textContent = result.otherCompany.name; document.getElementById('messageMeta').textContent = `${capabilityText(result.otherCompany)} · ${[result.otherCompany.city, result.otherCompany.state].filter(Boolean).join(', ')}`; document.getElementById('messageThread').innerHTML = result.messages.length ? result.messages.map(message => `<div class="message-bubble ${message.senderCompanyId === dashboard.company.id ? 'mine' : ''}"><strong>${escapeHtml(message.senderName)}</strong><p>${escapeHtml(message.body)}</p><small>${new Date(message.createdAt).toLocaleString()}</small></div>`).join('') : '<div class="message-empty compact"><span>Start the conversation. Introduce your company or discuss a project opportunity.</span></div>'; document.getElementById('messageThread').scrollTop = document.getElementById('messageThread').scrollHeight; renderConversations(); } catch (error) { showNotice(error.message, true); } }
document.getElementById('messageForm').addEventListener('submit', async event => { event.preventDefault(); if (!activeConversationId) return; const field = event.currentTarget.elements.body; try { await api(`/api/conversations/${activeConversationId}/messages`, { method: 'POST', body: JSON.stringify({ body: field.value }) }); field.value = ''; await refresh(); await openConversation(activeConversationId); } catch (error) { showNotice(error.message, true); } });
async function refresh() { dashboard = await api('/api/dashboard'); renderShell(); }
refresh().catch(() => { location.href = '/login'; });
