const TRADE_OPTIONS=['Appliance Installation','Asphalt Paving','Cabinetry','Carpentry','Cleaning','Concrete','Countertops','Demolition','Doors and Windows','Drywall','Electrical','Excavation','Fencing','Finish Carpentry','Fire Protection','Flooring','Framing','General Labor','Glass and Glazing','Gutters','HVAC','Insulation','Landscaping','Masonry','Metal Fabrication','Painting','Plumbing','Pool and Spa','Roofing','Siding','Solar','Stone and Tile','Structural Steel','Surveying','Waterproofing','Welding'];
const CITY_OPTIONS=['Arlington, TX','Austin, TX','Columbus, OH','Dallas, TX','Fort Worth, TX','Frisco, TX','Garland, TX','Houston, TX','Irving, TX','McKinney, TX','Plano, TX','San Antonio, TX'];
function canonicalTrade(value){const normalized=String(value||'').trim().toLowerCase();return TRADE_OPTIONS.find(option=>option.toLowerCase()===normalized)||''}
function addList(id,values){if(document.getElementById(id))return;const list=document.createElement('datalist');list.id=id;list.innerHTML=values.map(value=>`<option value="${value}"></option>`).join('');document.body.appendChild(list)}
function stateField(input){const scope=input.closest('form,fieldset,.form-row,.location-settings')||document;return scope.querySelector('[name="state"],#jobStateFilter')}
function applyCity(cityInput,description){const parts=String(description||'').split(',').map(value=>value.trim()),state=parts.at(-1);cityInput.value=parts[0]||description;const field=stateField(cityInput);if(field&&state&&state.length===2)field.value=state.toUpperCase();cityInput.dispatchEvent(new Event('input',{bubbles:true}))}
function enableFallbackCity(input){input.setAttribute('list','trades-city-options');input.placeholder=input.placeholder||'Start typing a city';input.addEventListener('change',()=>{const match=CITY_OPTIONS.find(value=>value.toLowerCase()===input.value.trim().toLowerCase());if(match)applyCity(input,match)},{once:false})}
function enableGoogleCity(input){if(!window.google?.maps?.places||input.dataset.googlePlacesReady)return;input.dataset.googlePlacesReady='true';const autocomplete=new google.maps.places.Autocomplete(input,{types:['(cities)'],componentRestrictions:{country:'us'},fields:['address_components','formatted_address','name']});autocomplete.addListener('place_changed',()=>{const place=autocomplete.getPlace(),components=place.address_components||[],city=components.find(x=>x.types.includes('locality'))?.long_name||components.find(x=>x.types.includes('postal_town'))?.long_name||place.name,state=components.find(x=>x.types.includes('administrative_area_level_1'))?.short_name;if(city)input.value=city;if(state){const field=stateField(input);if(field)field.value=state}input.dispatchEvent(new Event('input',{bubbles:true}))})}
function enableSingleTrade(input){if(input.dataset.tradeReady)return;input.dataset.tradeReady='true';input.setAttribute('list','trades-trade-options');input.placeholder=input.placeholder||'Start typing a trade';input.addEventListener('change',()=>{const match=canonicalTrade(input.value);if(match)input.value=match});const form=input.closest('form');if(form&&!form.dataset.tradeValidationReady){form.dataset.tradeValidationReady='true';form.addEventListener('submit',event=>{const fields=[...form.querySelectorAll('[data-trade-picker="single"]')];for(const field of fields){if(field.value&&!canonicalTrade(field.value)){event.preventDefault();event.stopImmediatePropagation();field.setCustomValidity('Select a trade from the standard list.');field.reportValidity();setTimeout(()=>field.setCustomValidity(''),2000);return}field.value=canonicalTrade(field.value)||field.value}},true)}}
function enableMultiTrade(root){if(root.dataset.tradeReady)return;root.dataset.tradeReady='true';const input=root.querySelector('[data-trade-add]'),hidden=root.querySelector('[name="trades"]'),chips=root.querySelector('[data-trade-chips]');input.setAttribute('list','trades-trade-options');let selected=String(hidden.value||'').split(',').map(canonicalTrade).filter(Boolean);function render(){hidden.value=selected.join(', ');chips.innerHTML=selected.map(trade=>`<button type="button" data-remove-trade="${trade}" aria-label="Remove ${trade}">${trade}<span>&times;</span></button>`).join('');chips.querySelectorAll('[data-remove-trade]').forEach(button=>button.onclick=()=>{selected=selected.filter(trade=>trade!==button.dataset.removeTrade);render()})}function add(){const trade=canonicalTrade(input.value);if(!trade){input.setCustomValidity('Select a trade from the standard list.');input.reportValidity();setTimeout(()=>input.setCustomValidity(''),2000);return}if(!selected.includes(trade))selected.push(trade);input.value='';render()}input.addEventListener('change',add);input.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();add()}});render()}
function enhancePickers(root=document){addList('trades-trade-options',TRADE_OPTIONS);addList('trades-city-options',CITY_OPTIONS);root.querySelectorAll('[name="trade"],#jobTradeFilter').forEach(input=>{input.dataset.tradePicker='single';enableSingleTrade(input)});root.querySelectorAll('[data-trade-picker="multi"]').forEach(enableMultiTrade);root.querySelectorAll('[name="city"],#jobCityFilter').forEach(input=>{if(input.dataset.cityReady)return;input.dataset.cityReady='true';enableFallbackCity(input);enableGoogleCity(input)});root.querySelectorAll('[name="state"],#jobStateFilter').forEach(input=>{input.maxLength=2;input.addEventListener('input',()=>input.value=input.value.toUpperCase())})}
async function loadGooglePlaces(){try{const response=await fetch('/api/public-config',{cache:'no-store'}),config=await response.json();if(!config.googleMapsApiKey)return;const script=document.createElement('script');script.src=`https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(config.googleMapsApiKey)}&libraries=places&callback=tradesGooglePlacesReady`;script.async=true;script.defer=true;document.head.appendChild(script)}catch(error){console.warn('Google Places unavailable; using standardized city fallback.',error)}}
window.tradesGooglePlacesReady=()=>enhancePickers();window.TradesTaxonomy={trades:TRADE_OPTIONS,canonicalTrade,enhancePickers};enhancePickers();new MutationObserver(records=>records.forEach(record=>record.addedNodes.forEach(node=>{if(node.nodeType===1)enhancePickers(node.matches?.('form,fieldset,section,article,div')?node:document)}))).observe(document.body,{childList:true,subtree:true});loadGooglePlaces();
